expression = term
term       = product ((PLUS | MINUS) term)?
product    = unary (DOT product | (quotient)+)?
unary      = (PLUS | MINUS) unary | exponent 
exponent   = quotient (CARET exponent)?
quotient   = func | FRACTION quotient quotient
func       = (SIN | COS | TAN | SQRT | LN | LOG) func | primary 
primary    = REAL | IDENTIFIER | PARAMETER | LEFT_PAREN expression RIGHT_PAREN